package main

import (
	"encoding/json"
	"os"
)

// config holds all runtime configuration for the gossip agent.
// Loaded from a JSON file at startup.
type config struct {
	// ListenAddr is the TCP address the gossip server binds to.
	// Example: "0.0.0.0:7946"
	ListenAddr string `json:"listen_addr"`

	// WireGuardAddr is the WireGuard endpoint announced in NodeRecord.
	// Example: "203.0.113.1:51820"
	WireGuardAddr string `json:"wireguard_addr"`

	// GTPAddr is the GTP-U endpoint announced in NodeRecord.
	// Example: "203.0.113.1:2152"
	GTPAddr string `json:"gtp_addr"`

	// BootstrapPeers is the list of known peers to contact on startup.
	// Spec reference: Section 9.2 — bootstrap node handling.
	// At least one is required for a new node joining the network.
	BootstrapPeers []string `json:"bootstrap_peers"`

	// DataDir is where the node keypair is persisted.
	DataDir string `json:"data_dir"`

	// Regions are the ISO 3166-1 alpha-2 country codes where SIMs are registered.
	Regions []string `json:"regions"`

	// Jurisdictions are the legal jurisdictions governing this server's data.
	// Spec reference: Section 10.2 — used in circuit construction for diversity.
	Jurisdictions []string `json:"jurisdictions"`

	// ExitNode declares whether this server will route traffic to the internet.
	// Spec reference: Section 5.5 — exit_node capability flag.
	ExitNode bool `json:"exit_node"`

	// MaxCircuits is the maximum number of concurrent circuits this node supports.
	MaxCircuits int `json:"max_circuits"`

	// WireGuardPubKey is the WireGuard public key for this node.
	// Generated by camo-wireguard and referenced here for NodeRecord announcement.
	WireGuardPubKey string `json:"wireguard_pubkey"`
}

// defaultConfig returns a config with safe defaults.
func defaultConfig() *config {
	return &config{
		ListenAddr:  "0.0.0.0:7946",
		DataDir:     "/var/lib/camo",
		MaxCircuits: 100,
	}
}

// loadConfig reads a JSON config file from path.
// Fields not present in the file retain their default values.
func loadConfig(path string) (*config, error) {
	cfg := defaultConfig()
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	if err := json.Unmarshal(data, cfg); err != nil {
		return nil, err
	}
	return cfg, nil
}
